import type OneCalendar from './main';
import {calendarUrl} from './caldav';
import {button} from './forms';
import {safeColor} from './calendar-sources';

export function renderCalDavSettings(root:HTMLElement,plugin:OneCalendar){
  const section=root.createDiv();const redraw=()=>{section.empty();renderContents(section,plugin,redraw);};redraw();
}
function renderContents(root:HTMLElement,plugin:OneCalendar,redraw:()=>void){
  root.createEl('h3',{text:'My calendars'});
  root.createEl('p',{cls:'tc-muted',text:'Add calendars from the same account or different servers. Colors identify their events. Passwords must be configured on each device. The connection form below is also the task reminder target.'});
  for(const s of plugin.settings.caldavSources??[]){
    const row=root.createDiv({cls:'tc-calendar-source'});
    const enabled=row.createEl('input',{type:'checkbox',attr:{'aria-label':`Enable ${s.name}`}});enabled.checked=s.enabled;enabled.onchange=()=>void plugin.run(()=>plugin.updateCalendarSource(s.id,{enabled:enabled.checked}));
    const name=row.createEl('input',{value:s.name,attr:{'aria-label':`Calendar name ${s.name}`}});name.onchange=()=>void plugin.run(()=>plugin.updateCalendarSource(s.id,{name:name.value.trim()||'Calendar'}));
    const color=row.createEl('input',{type:'color',value:safeColor(s.color),attr:{'aria-label':`Color for ${s.name}`}});color.onchange=()=>void plugin.run(()=>plugin.updateCalendarSource(s.id,{color:color.value}));
    row.createSpan({cls:'tc-muted',text:s.readOnly?'Read only':'Write access depends on server'});
    button(row,'Connection',async()=>{await plugin.editCalendarSource(s.id);redraw();});
    button(row,'Remove',async()=>{await plugin.removeCalendarSource(s.id);redraw();});
  }
  button(root,'Add another connection',async()=>{await plugin.newCalendarConnection();redraw();});
  const panel=root.createDiv({cls:'tc-caldav-setup'});
  panel.createEl('p',{text:'1. Connect to your server. 2. Select a calendar. 3. Add / update calendar. 4. Pull events. To add more calendars on this account, select each and add it. A server address such as caldav.feishu.cn works; HTTPS is added automatically.'});
  const field=(name:string,value='',type='text')=>{const row=panel.createEl('label',{cls:'tc-field'});row.createSpan({text:name});return row.createEl('input',{type,value,attr:{autocomplete:'off'}});};
  const server=field('CalDAV server or calendar URL',plugin.settings.caldavUrl??'');
  const username=field('CalDAV username',plugin.settings.caldavUsername??'');
  const password=field('CalDAV app password','','password');
  panel.createEl('p',{cls:'tc-muted',text:plugin.calDavPassword()?'A password is available for this connection. Leave the password field blank to keep it.':'Enter the CalDAV password generated by your service. Connecting uses it for this session; secure saving is optional.'});
  const actions=panel.createDiv({cls:'tc-actions'});
  const selectionLabel=panel.createEl('label',{cls:'tc-field'});selectionLabel.createSpan({text:'Calendar'});const selection=selectionLabel.createEl('select',{attr:{'aria-label':'Calendar'}});
  const details=panel.createDiv({cls:'tc-muted'});
  const status=panel.createDiv({cls:'tc-calendar-status',attr:{role:'status','aria-live':'polite'}});
  const preview=panel.createDiv({cls:'tc-calendar-preview'});
  let busy=false;
  const message=(text:string,error=false)=>{plugin.caldavStatus=text;status.setText(text);status.toggleClass('tc-error',error);};
  const options=()=>{
    selection.empty();selection.createEl('option',{value:'',text:'Select a calendar…'});
    for(const c of plugin.settings.caldavCalendars??[])selection.createEl('option',{value:c.url,text:c.name+(c.readOnly?' (read only)':'')});
    selection.value=plugin.settings.caldavCalendarUrl??'';
    const selected=plugin.settings.caldavCalendars?.find(c=>c.url===selection.value);
    details.setText(selected?`${selected.url}\n${selected.readOnly?'Server reports read-only access; task reminder writing is unavailable.':'Reading does not prove write access. Reminder writes may be restricted by the service.'}`:'No calendar selected. Click Connect & discover calendars first.');
  };
  const run=async(label:string,fn:()=>Promise<void>)=>{
    if(busy)return;busy=true;message(label);
    panel.querySelectorAll<HTMLInputElement|HTMLButtonElement|HTMLSelectElement>('input,button,select').forEach(e=>e.disabled=true);
    try{await fn();}catch(e){message((e as Error).message,true);}
    finally{busy=false;panel.querySelectorAll<HTMLInputElement|HTMLButtonElement|HTMLSelectElement>('input,button,select').forEach(e=>e.disabled=false);options();}
  };
  const apply=async()=>{
    const address=calendarUrl(server.value),user=username.value.trim(),entered=password.value;
    let previous='';try{previous=calendarUrl(plugin.settings.caldavUrl??'');}catch{}
    if(previous===address)plugin.settings.caldavUrl=address;
    else await plugin.changeCalDavConnection('caldavUrl',address);
    await plugin.changeCalDavConnection('caldavUsername',user);
    if(entered){plugin.sessionCalDavPassword=entered;password.value='';}
    server.value=address;await plugin.saveSettings();
    if(!plugin.calDavPassword())throw Error('Enter your CalDAV app password, then click Connect & discover calendars.');
  };
  const unchanged=()=>{
    if(calendarUrl(server.value)!==calendarUrl(plugin.settings.caldavUrl??'')||username.value.trim()!==plugin.settings.caldavUsername||password.value)throw Error('Connection fields changed. Click Connect & discover calendars first.');
  };
  button(actions,'Connect & discover calendars',()=>run('Connecting and discovering calendars…',async()=>{
    await apply();const calendars=await plugin.discoverCalDav();preview.empty();
    message(`Connected. Found ${calendars.length} calendar(s). ${plugin.settings.caldavCalendarUrl?'Calendar selected. Click Pull events now.':'Select a calendar below, then click Pull events now.'}`);
  }),'mod-cta');
  button(actions,'Pull events now',()=>run('Pulling events…',async()=>{
    unchanged();await plugin.pullCalDav();preview.empty();
    message(`${plugin.calendarStatus}. ${plugin.externalEvents.length?'Preview below; open the dashboard Calendar to browse all events.':'No events in the requested date range. Create a remote event, then pull again.'}`);
    for(const event of plugin.externalEvents.slice(0,5))preview.createDiv({text:`${event.title} · ${event.allDay?'All day':new Date(event.start).toLocaleString('en-US')}`});
  }));
  button(actions,'Add / update calendar',()=>run('Saving calendar…',async()=>{unchanged();await plugin.addCurrentCalendar();plugin.caldavStatus='Calendar added. Pull events now to refresh all enabled calendars. Save password securely to retain access after restarting.';redraw();}));
  button(actions,'Sync task reminders now',()=>run('Syncing task reminders…',async()=>{
    unchanged();if(!plugin.settings.caldavCalendarUrl)throw Error('Connect and select a calendar first.');
    if(plugin.settings.caldavCalendars?.find(c=>c.url===selection.value)?.readOnly)throw Error('This calendar is read only. Select a writable calendar for reminders.');
    if(!plugin.settings.writeEnabled)throw Error('Enable Write task reminders to calendar below before syncing reminders.');
    await plugin.syncReminders(true);const rows=plugin.store.all('reminder').filter(r=>r.data.provider==='caldav');
    const failed=rows.filter(r=>r.data.status==='Sync failed');
    message(failed.length?`${failed.length} reminder(s) failed: ${failed[0].data.error}`:`Reminder sync finished. ${rows.filter(r=>r.data.status==='Synced').length} synced, ${rows.filter(r=>!['Synced','Cancelled'].includes(r.data.status??'')).length} pending. Check your remote calendar; phone notification delivery is separate.`,!!failed.length);
  }));
  if(plugin.app.secretStorage)button(actions,'Save password securely',()=>run('Saving credentials…',async()=>{
    await apply();plugin.app.secretStorage.setSecret(plugin.settings.caldavSecretName??'task-calendar-caldav-password',plugin.calDavPassword());
    message('Password saved in Obsidian secret storage. Click Connect & discover calendars to test it.');
  }));
  button(actions,'Disconnect password',()=>run('Disconnecting…',async()=>{
    plugin.sessionCalDavPassword='';password.value='';plugin.sourcePasswords.delete(plugin.settings.caldavSecretName??'task-calendar-caldav-password');plugin.app.secretStorage?.setSecret(plugin.settings.caldavSecretName??'task-calendar-caldav-password','');
    message('Password disconnected. Existing remote reminders have not been deleted.');
  }));
  selection.onchange=()=>{const url=selection.value;if(url)void run('Selecting calendar…',async()=>{unchanged();await plugin.selectCalDav(url);preview.empty();message('Calendar selected. Click Pull events now.');});};
  options();message(plugin.caldavStatus);
  panel.createEl('p',{cls:'tc-muted',text:'Connection discovery and pulling are read-only. Automatic refresh is controlled below. CalDAV requires Basic authentication; service-specific write restrictions still apply. Android notifications require calendar synchronization and a calendar app.'});
}

